### ISSUE TITLE
Question: Tried compatability / suitablility when used with TCA?

### ISSUE THREAD

**Issue by Sajjon** [johnpatrickmorgan/NavigationBackport#14]
Hey John Patrick, another awesome project by you :) 

Have you tried using `NavigationBackport` in a TCA app? Does it play well together? 

[The navigation discussion thread in TCA](https://github.com/pointfreeco/swift-composable-architecture/discussions/1140) seemed to state that the new navigation API does not play well together with TCA :/

I think [TCACoordinators](https://github.com/johnpatrickmorgan/TCACoordinators) is a good alternative, but like the new SwiftUI Navigation API a lot but need back port to iOS 15, so I was glad to find this repo! :)

**Comment by johnpatrickmorgan** [comment]
Thanks @Sajjon ! I haven't done much exploration of how this could fit into TCA. From my understanding, the difficulties described in that thread are due to the fairly limited API surface provided by the new navigation APIs. `NavigationBackport` replicates those APIs, so it would produce the same difficulties. 

Looking at the list of additional APIs that would be desirable for integrating better with TCA, I believe they could all be added in this library. However, at the moment the ethos of this library is to match the SwiftUI API surface without offering any additional APIs, so that users can easily migrate away from this library when they are able to bump their deployment target high enough. 

I believe the pointfree team are making progress on new navigation functionality within TCA, so perhaps they have been able to overcome some of those difficulties.
