### ISSUE TITLE
Is there anyway to call (or inject) PathNavigator in ObservableObject Class?

### ISSUE THREAD

**Issue by ajinumoto** [johnpatrickmorgan/NavigationBackport#50]
Lets say after some process in `SomeClass` it will pop the screen

```
class SomeClass: ObservableObject {
    
    private let navigator: PathNavigator
        
    init(navigator: PathNavigator) {
        self.navigator = navigator
        someRemoteProcess()
    }

    func popScreen() {
        navigator.pop()
    }
    
    func someRemoteProcess() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.popScreen()
        }
    }
}
```

Is there anyway i can achieve this. Thank you

**Comment by johnpatrickmorgan** [comment]
Unfortunately there's no way to have SwiftUI environment variables available outside the view layer, e.g. in an observable object like a ViewModel. There are some third-party libs such as [swift-dependencies](https://github.com/pointfreeco/swift-dependencies) that do allow you to propagate dependencies outside the view layer. Otherwise, I can see a couple of options:
- pass the dependency from the view to the view model, e.g. `func someRemoteProcess(navigator: PathNavigator) { ...}`.
- handle the navigation in the view layer, after waiting for the view model to do its work, e.g. `func someRemoteProcess() async { ...}`.
