### ISSUE TITLE
In iOS 15, when an app with background mode enabled sequentially pushes two view controllers while in the background, it will open both view controllers when the app returns to the foreground. However, the last view controller will be popped off.

### ISSUE THREAD

**Issue by ffengyuepingfen** [johnpatrickmorgan/NavigationBackport#53]
In iOS 15, when an app with background mode enabled sequentially pushes two view controllers while in the background, it will open both view controllers when the app returns to the foreground. However, the last view controller will be popped off.

Start background：
![image](https://github.com/user-attachments/assets/e47c7362-6e0a-4499-a53b-d9a24df786cc)

Two pages are then opened by counting down

**Comment by ffengyuepingfen** [comment]
[NaviBackportExample-main.zip](https://github.com/user-attachments/files/16632444/NaviBackportExample-main.zip)
Here is a demo for iOS 15, with the following steps:

	1.	Launch the app and navigate to the first page.
	2.	Send the app to the background.
	3.	Wait for the console to print “第三个来了 .”
	4.	Return to the foreground and see the third page.

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue @ffengyuepingfen and for the reproduction. I can see the issue you describe in the reproduction project. I suspect it happens because:

- On iOS 15, only one screen can be pushed at a time, so this library breaks down such changes into smaller changes separated by a delay. Side note, you should no longer need to call `withDelaysIfUnsupported` yourself, as the library handles this automatically now.
- But SwiftUI doesn't fully react to navigation state changes until the app becomes active, at which point the state change is more than a single screen push, so it fails.

I'm wondering if this library should therefore wait until the app comes out of the background before it updates its internal navigation state.

**Comment by ffengyuepingfen** [comment]
ok , thanks for your reply

**Comment by johnpatrickmorgan** [comment]
Hi @ffengyuepingfen , I believe this issue should be resolved in `v0.9.5`. The library will now delay any navigation state updates until after the app becomes active again, when using `NavigationView` (e.g. on iOS 15).

**Comment by ffengyuepingfen** [comment]
Thank you very much. My problem has been solved.
