### ISSUE TITLE
Disclosure chevron in List?

### ISSUE THREAD

**Issue by aehlke** [johnpatrickmorgan/NavigationBackport#55]
NavigationLink is used under the hood in this library when available, but for some reason that's not enough to get List cell disclosure chevrons to appear. When I switch to NavigationLink, the chevron appears per row. I can't get them to appear with this library though. Is there a workaround? Thank you

**Comment by johnpatrickmorgan** [comment]
Hi @aehlke, thanks for raising this. There's a good discussion of this problem in the [swift-navigation library](https://github.com/pointfreeco/swift-navigation/discussions/37), and @tgrapperon has done some great work recreating the `NavigationLink` behaviour as a button style. I've added a simpler button style that should give you the chevron at least (but not the cell highlighting behaviour), which is available in `v0.9.6` by adding `.buttonStyle(.navigationLinkRowStyle)` to a `NBNavigationLink` within a `List`. And you should be able to add your own button style if you want to customise the behaviour any further.

**Comment by johnpatrickmorgan** [comment]
Thanks for your work on those button styles @tgrapperon - I saw some different approaches you had taken, and was curious what approach you eventually landed on? When I experimented with [this one](https://gist.github.com/tgrapperon/e92d7699b2a6ca8093bdf2cb1abb3376/revisions), I didn't see the cell highlighting behaviour because it didn't seem to find a `UICollectionView` in the UI view hierarchy.
